const members = [
  // Tower 1A
  { flatNo: "1A-101", name: "ASIS MAJUMBER", password: "asi1a101", briefDescription: "Details will be updated later" },
  { flatNo: "1A-102", name: "ANUPAM MUKHERJEE", password: "anu1a102", briefDescription: "Details will be updated later" },
  { flatNo: "1A-103", name: "GITA SHAHA", password: "git1a103", briefDescription: "Details will be updated later" },
  { flatNo: "1A-104", name: "CHANDAN SAHA", password: "cha1a104", briefDescription: "Details will be updated later" },
  { flatNo: "1A-201", name: "TAPABRATA BHAKTA", password: "tap1a201", briefDescription: "Details will be updated later" },
  { flatNo: "1A-202", name: "RINKI GHOSH", password: "rin1a202", briefDescription: "Details will be updated later" },
  { flatNo: "1A-203", name: "NANDINI DAS", password: "nan1a203", briefDescription: "Details will be updated later" },
  { flatNo: "1A-204", name: "SUBHENDU SEN", password: "sub1a204", briefDescription: "Details will be updated later" },
  { flatNo: "1A-301", name: "POLLY MALLICK", password: "mrs1a301", briefDescription: "Details will be updated later" },
  { flatNo: "1A-302", name: "ARATI BANERJEE", password: "ara1a302", briefDescription: "Details will be updated later" },
  { flatNo: "1A-303", name: "MALINI DATTA", password: "mal1a303", briefDescription: "Details will be updated later" },
  { flatNo: "1A-304", name: "SIKHA GHOSH", password: "sik1a304", briefDescription: "Details will be updated later" },
  { flatNo: "1A-401", name: "SARADA KUNDU", password: "sar1a401", briefDescription: "Details will be updated later" },
  { flatNo: "1A-402", name: "MOU CHOUDHURI", password: "mou1a402", briefDescription: "Details will be updated later" },
  { flatNo: "1A-403", name: "INDRANI BISWAS", password: "ind1a403", briefDescription: "Details will be updated later" },
  { flatNo: "1A-404", name: "RITUPARNA GHOSE", password: "rit1a404", briefDescription: "Details will be updated later" },

  // Tower 2A
  { flatNo: "2A-101", name: "BHARATI RAY", password: "bha2a101", briefDescription: "Details will be updated later" },
  { flatNo: "2A-102", name: "SEKHAR DAS", password: "sek2a102", briefDescription: "Details will be updated later" },
  { flatNo: "2A-103", name: "SOUMITRA BERA", password: "sou2a103", briefDescription: "Details will be updated later" },
  { flatNo: "2A-104", name: "ANITA ADHIKARY", password: "ani2a104", briefDescription: "Details will be updated later" },
  { flatNo: "2A-201", name: "ADITI DAS", password: "adi2a201", briefDescription: "Details will be updated later" },
  { flatNo: "2A-202", name: "BIBHUTI BHUSHAN PATRA", password: "bib2a202", briefDescription: "Details will be updated later" },
  { flatNo: "2A-203", name: "ARCHANA MAJUMDER", password: "arc2a203", briefDescription: "Details will be updated later" },
  { flatNo: "2A-204", name: "ARIJIT BHATTACHARYA", password: "ari2a204", briefDescription: "Details will be updated later" },
  { flatNo: "2A-301", name: "ROMA DUTTA", password: "p.k2a301", briefDescription: "Details will be updated later" },
  { flatNo: "2A-302", name: "MANJU DAS", password: "man2a302", briefDescription: "Details will be updated later" },
  { flatNo: "2A-303", name: "TANUKA DAS", password: "tan2a303", briefDescription: "Details will be updated later" },
  { flatNo: "2A-304", name: "SUSMITA HALDER", password: "sus2a304", briefDescription: "Details will be updated later" },
  { flatNo: "2A-401", name: "DEBOJIT SEN", password: "deb2a401", briefDescription: "Details will be updated later" },
  { flatNo: "2A-402", name: "AYAN BANERJEE", password: "aya2a402", briefDescription: "Details will be updated later" },
  { flatNo: "2A-403", name: "BIVASH CHATTERJEE", password: "biv2a403", briefDescription: "Details will be updated later" },
  { flatNo: "2A-404", name: "NILOY KANTI PANDIT & ANINDITA LAHIRI PANDIT", password: "nil2a404", briefDescription: "Details will be updated later" },

  // Tower 3A
  { flatNo: "3A-101", name: "PRAMILA TEWARI", password: "pra3a101", briefDescription: "Details will be updated later" },
  { flatNo: "3A-102", name: "PAMELA BOSE", password: "pam3a102", briefDescription: "Details will be updated later" },
  { flatNo: "3A-103", name: "JAY KRISHNA DAS", password: "jay3a103", briefDescription: "Details will be updated later" },
  { flatNo: "3A-104", name: "UTTAM GHOSH", password: "sri3a104", briefDescription: "Details will be updated later" },
  { flatNo: "3A-201", name: "PRADIP GUHA ROY", password: "sri3a201", briefDescription: "Details will be updated later" },
  { flatNo: "3A-202", name: "MITALI PAL", password: "mit3a202", briefDescription: "Details will be updated later" },
  { flatNo: "3A-203", name: "KAUSTAV KARMAKAR", password: "kau3a203", briefDescription: "Details will be updated later" },
  { flatNo: "3A-204", name: "SARBANI CHAKRAVARTI", password: "sar3a204", briefDescription: "Details will be updated later" },
  { flatNo: "3A-301", name: "RATNABALI DUTTA", password: "rat3a301", briefDescription: "Details will be updated later" },
  { flatNo: "3A-302", name: "TAPAN KUMAR BARUA", password: "tap3a302", briefDescription: "Details will be updated later" },
  { flatNo: "3A-303", name: "ATMADIPA MUKHERJEE", password: "atm3a303", briefDescription: "Details will be updated later" },
  { flatNo: "3A-304", name: "SWAPNA BASAK", password: "swa3a304", briefDescription: "Details will be updated later" },
  { flatNo: "3A-401", name: "PRANAB KUMAR BHOWMICK", password: "pra3a401", briefDescription: "Details will be updated later" },
  { flatNo: "3A-402", name: "ANURAG SINGH", password: "anu3a402", briefDescription: "Details will be updated later" },
  { flatNo: "3A-403", name: "GANESH CHANDRA SEN", password: "gan3a403", briefDescription: "Details will be updated later" },
  { flatNo: "3A-404", name: "LILY SARKAR", password: "lil3a404", briefDescription: "Details will be updated later" },

  // Tower 4A
  { flatNo: "4A-101", name: "SANJIB KUNDU", password: "san4a101", briefDescription: "Details will be updated later" },
  { flatNo: "4A-102", name: "DINABANDHU GANGHOPADHYAY", password: "din4a102", briefDescription: "Details will be updated later" },
  { flatNo: "4A-103", name: "PRASANTA GHOSH", password: "pra4a103", briefDescription: "Details will be updated later" },
  { flatNo: "4A-104", name: "SOMNATH JHA", password: "som4a104", briefDescription: "Details will be updated later" },
  { flatNo: "4A-201", name: "SUSMITA DAS", password: "sus4a201", briefDescription: "Details will be updated later" },
  { flatNo: "4A-202", name: "ANJANA MITRA", password: "anj4a202", briefDescription: "Details will be updated later" },
  { flatNo: "4A-203", name: "KALYAN PAL", password: "kal4a203", briefDescription: "Details will be updated later" },
  { flatNo: "4A-204", name: "KANIKA BHATTACHARYA", password: "kan4a204", briefDescription: "Details will be updated later" },
  { flatNo: "4A-301", name: "GANESH TEWARI", password: "gan4a301", briefDescription: "Details will be updated later" },
  { flatNo: "4A-302", name: "GOURANGA DAS", password: "gou4a302", briefDescription: "Details will be updated later" },
  { flatNo: "4A-303", name: "BISWANATH MUKHERJEE", password: "bis4a303", briefDescription: "Details will be updated later" },
  { flatNo: "4A-304", name: "SWARNAVO ROY", password: "swa4a304", briefDescription: "Details will be updated later" },
  { flatNo: "4A-401", name: "SHAURYYA CHAKRABORTY", password: "sha4a401", briefDescription: "Details will be updated later" },
  { flatNo: "4A-402", name: "NANI GOPAL GOSWAMI", password: "nan4a402", briefDescription: "Details will be updated later" },
  { flatNo: "4A-403", name: "HIMSEKHAR DUTTA", password: "him4a403", briefDescription: "Details will be updated later" },
  { flatNo: "4A-404", name: "MILI ROY", password: "mil4a404", briefDescription: "Details will be updated later" }
];
